### ISSUE TITLE
Found more water seams

### ISSUE THREAD

**Issue by Kyle-sys** [PierreDespereaux/Keizaal#79] opened 2021-01-19 19:29 UTC
**Keizaal version**
3.5.1.2

**Describe the bug**
Hopefully title is enough

**To reproduce**
I just followed the river, that the Guardian Stones overlook.

**Expected behavior**
No water seams if possible.

**Screenshots**
![Skyrim Special Edition 1_19_2021 2_09_54 PM](https://user-images.githubusercontent.com/52866222/105082839-22149080-5a62-11eb-925a-cf5223fb2d17.png)
![Skyrim Special Edition 1_19_2021 2_10_21 PM](https://user-images.githubusercontent.com/52866222/105082844-23de5400-5a62-11eb-8f52-895274d8528c.png)
![Skyrim Special Edition 1_19_2021 2_11_31 PM](https://user-images.githubusercontent.com/52866222/105082850-25a81780-5a62-11eb-9795-a02cb7232b0e.png)
![Skyrim Special Edition 1_19_2021 2_21_26 PM](https://user-images.githubusercontent.com/52866222/105082859-280a7180-5a62-11eb-9d15-da3072eabc0d.png)
![Skyrim Special Edition 1_19_2021 2_22_43 PM](https://user-images.githubusercontent.com/52866222/105082865-29d43500-5a62-11eb-86cd-99f2039fea73.png)
![Skyrim Special Edition 1_19_2021 2_42_26 PM](https://user-images.githubusercontent.com/52866222/105084692-b3850200-5a64-11eb-9d9c-d473287712b1.png)
![Skyrim Special Edition 1_19_2021 2_42_39 PM](https://user-images.githubusercontent.com/52866222/105084695-b5e75c00-5a64-11eb-84df-8bfc37e7836f.png)
![Skyrim Special Edition 1_19_2021 2_54_35 PM](https://user-images.githubusercontent.com/52866222/105086341-e62ffa00-5a66-11eb-97ae-373948517837.png)
![Skyrim Special Edition 1_19_2021 2_54_49 PM](https://user-images.githubusercontent.com/52866222/105086367-eb8d4480-5a66-11eb-8070-eaaf71c89d5d.png)
![Skyrim Special Edition 1_19_2021 2_55_06 PM](https://user-images.githubusercontent.com/52866222/105086382-ee883500-5a66-11eb-87c5-8d1ef445db9f.png)
![Skyrim Special Edition 1_19_2021 3_04_57 PM](https://user-images.githubusercontent.com/52866222/105087078-f72d3b00-5a67-11eb-9ce2-fd790f7905e8.png)
![Skyrim Special Edition 1_19_2021 3_05_21 PM](https://user-images.githubusercontent.com/52866222/105087087-fac0c200-5a67-11eb-8e05-9d11ce416733.png)
![Skyrim Special Edition 1_19_2021 3_07_14 PM](https://user-images.githubusercontent.com/52866222/105087249-35c2f580-5a68-11eb-9fda-363e2ce6962c.png)
![Skyrim Special Edition 1_19_2021 3_15_18 PM](https://user-images.githubusercontent.com/52866222/105088005-5475bc00-5a69-11eb-9adc-ec78dca587b9.png)
![Skyrim Special Edition 1_19_2021 3_15_34 PM](https://user-images.githubusercontent.com/52866222/105088030-5b9cca00-5a69-11eb-9be0-e5d22f03bd9d.png)
![Skyrim Special Edition 1_19_2021 3_15_46 PM](https://user-images.githubusercontent.com/52866222/105088046-5f305100-5a69-11eb-905a-82b7a1a20376.png)

**Additional context**
I hope the screenshots help narrow down where the water seams are at. If you need any more information from me, let me know and ill try my best to give you it.

**Comment by PierreDespereaux** [comment] 2021-01-19 19:32
bro you give the best bug reports

**Comment by Kyle-sys** [comment] 2021-01-19 19:33
Ty, I try my best.

**Comment by Kyle-sys** [comment] 2021-01-19 19:38
Oof just found another I’ll update this post with more screenshots if I keep finding more.

**Comment by PierreDespereaux** [comment] 2021-01-22 03:03
Duplicate of #78

**Comment by PierreDespereaux** [comment] 2021-01-22 03:03
Fixed

**Closed by PierreDespereaux** 2021-01-22 03:03 UTC
Labels: bug, fixed
