### ISSUE TITLE
Shadows not rendering while moving.

### ISSUE THREAD

**Issue by ThePixel23** [PierreDespereaux/Keizaal#29] opened 2020-12-13 05:29 UTC
Version 3.4.0

Sometimes after fast travelling or otherwise loading into particularity dense areas such town will cause a lighting bug where shadows won't render while you are moving.

I couldn't get this bug to happen consistently, it would only happen sporadically when loading into towns.

While the bug is active shadows won't appear to render while you are moving, when you stand still everything looks normal.
They're appears to be no performance degradation or other effects, and no CTDs occurred while under it's effects.

 These videos linked show the bug quite well, [link](https://www.youtube.com/watch?v=SMhZsVhmdAY&list=PL1rrgggAgLh6_0-ZOnX5xRT-LiiBA1yVO&index=2).

**Comment by PierreDespereaux** [comment] 2020-12-18 04:58
Duplicate of #28

**Comment by PierreDespereaux** [comment] 2020-12-31 06:33
Over two weeks without any further reports of the bug. Assumed resolved.

**Closed by PierreDespereaux** 2020-12-31 06:33 UTC
Labels: bug, duplicate
