### ISSUE TITLE
Weird Bug at the Bleaks Falls Temple when in First Person View

### ISSUE THREAD

**Issue by Kyle-sys** [PierreDespereaux/Keizaal#111] opened 2021-02-08 16:03 UTC
**Keizaal version**
4.0.2.4

**Describe the bug**
This bug seems to occur only in First Person View, Third Person View is fine.

**To reproduce**
Go to Bleaks Falls Temple where the lever is with the dead bandit and find the other lever that is on the wall of the gate and just simply look into it.

**Expected behavior**
For the wall to look normal even if you look right up close to it.

**Screenshots**
![Skyrim Special Edition 2_8_2021 11_00_43 AM](https://user-images.githubusercontent.com/52866222/107245278-f7807c80-69fc-11eb-88c3-382a382515b9.png)
![Skyrim Special Edition 2_8_2021 10_59_47 AM](https://user-images.githubusercontent.com/52866222/107245294-fd765d80-69fc-11eb-8b6c-64effa3f2f47.png)
![Skyrim Special Edition 2_8_2021 10_44_27 AM](https://user-images.githubusercontent.com/52866222/107245309-00714e00-69fd-11eb-8050-1efcf7f2b9fc.png)
![Skyrim Special Edition 2_8_2021 10_44_06 AM](https://user-images.githubusercontent.com/52866222/107245319-036c3e80-69fd-11eb-9641-629fa0e95f74.png)

**Video**
https://youtu.be/0zrK2b7U5vI

**Additional context**
I only enabled Skyrim Unbound Reborn and moved it just above the Keziaal plugins.

**Comment by PierreDespereaux** [comment] 2021-02-08 16:09
So this is caused by inproper room and portal layouts.

"Rooms and portals" have a different definition when it comes to the Creation Kit. A "room" is an area is a dungeon contained within an occlusion plane. These are connected together with "portals". This is done to preserve performance as only things in the room you are in are rendered. The player should never notice going between two rooms, but sometimes improper layout can lead to stuff like this. Basically the portal isn't place in quite the right place and you're seeing into the next "room" before it's rendered.

That was a lot of technical speak that may have been a bit confusing. This isn't something I really want to fix as the author should probably be made aware of it. I'm going to tag this as "wontfix" and relay your bug report to the author.

It will be kept open for reference until the author does fix it ~~or I decide to fix it anyway~~.

**Comment by Kyle-sys** [comment] 2021-02-08 16:11
Ah okay, ty for the explanation.

**Closed** 2021-04-23 15:38 UTC
Labels: bug, wontfix
